/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package is2;

import java.awt.Component;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

import Asignaturas.Asignatura;
import Controller.Controller;
import Grupos.PanelAltaGrupo;
import Usuarios.Alumno;
import Usuarios.Profesor;

/**
 *
 * @author stele
 */
public class DialogoAlta extends javax.swing.JDialog {

	int selectedIndex;
	private Controller _ctrl;
	private Frame padre;
	ArrayList<JTextField> lista = new ArrayList<>();

	/**
	 * Creates new form DialogoOpciones
	 */
	public DialogoAlta(java.awt.Frame parent, boolean modal, Controller control) {
		super(parent, modal);
		Frame padre = parent;
		_ctrl = control;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel2 = new javax.swing.JPanel();
		jLabel19 = new javax.swing.JLabel();
		jLabel20 = new javax.swing.JLabel();
		jTextField19 = new javax.swing.JTextField();
		jTextField20 = new javax.swing.JTextField();
		jLabel21 = new javax.swing.JLabel();
		jTextField21 = new javax.swing.JTextField();
		jTextField22 = new javax.swing.JTextField();
		jLabel22 = new javax.swing.JLabel();
		jPanel3 = new javax.swing.JPanel();
		IDTextField = new javax.swing.JTextField();
		creditosTextField = new javax.swing.JTextField();
		nombreAsignaturaTextField = new javax.swing.JTextField();
		nombreAsignaturaLabel = new javax.swing.JLabel();
		creditosLabel = new javax.swing.JLabel();
		IDLabel = new javax.swing.JLabel();
		panelCurso = new javax.swing.JPanel();
		jLabelAnio = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		panelGrupos = new javax.swing.JPanel();////
		nombreGrupo = new javax.swing.JLabel();
		nombreGrupoTextField = new javax.swing.JTextField();////
		jPanel6 = new javax.swing.JPanel();
		jLabel5 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		panelAlumnos = new javax.swing.JPanel();
		nombreAlumnosLabel = new javax.swing.JLabel();
		apellidosAlumnosLabel = new javax.swing.JLabel();
		apellidosAlumnosTextField = new javax.swing.JTextField();
		nombreAlumnosTextField = new javax.swing.JTextField();
		correoAlumnosLabel = new javax.swing.JLabel();
		correoAlumnosTextField = new javax.swing.JTextField();
		dniAlumnosTextField = new javax.swing.JTextField();
		dniAlumnosLabel = new javax.swing.JLabel();
		saveButton = new javax.swing.JButton();
		cancelButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Dar de alta");
		setResizable(false);

		jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
			public void stateChanged(javax.swing.event.ChangeEvent evt) {
				jTabbedPane1StateChanged(evt);
			}
		});

		jLabel19.setText("Correo");

		jLabel20.setText("Apellidos");

		jTextField19.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField19ActionPerformed(evt);
			}
		});

		jTextField20.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField20ActionPerformed(evt);
			}
		});

		jLabel21.setText("Nombre");

		jLabel22.setText("DNI");

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel2Layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel21)
								.addComponent(jLabel20).addComponent(jLabel22).addComponent(jLabel19))
						.addGap(33, 33, 33)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
								.addComponent(jTextField20, javax.swing.GroupLayout.Alignment.LEADING,
										javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
								.addComponent(jTextField19, javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jTextField21, javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jTextField22))
						.addContainerGap(184, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(26, 26, 26)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel21))
						.addGap(18, 18, 18)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel20))
						.addGap(18, 18, 18)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel19))
						.addGap(18, 18, 18)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel22))
						.addContainerGap(191, Short.MAX_VALUE)));

		jTabbedPane1.addTab("Profesor", jPanel2);

		nombreAsignaturaTextField.setText(" ");
		nombreAsignaturaTextField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField4ActionPerformed(evt);
			}
		});

		nombreAsignaturaLabel.setText("Asignatura:");

		creditosLabel.setText("Nº Créditos:");

		IDLabel.setText("ID Único:");

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(creditosLabel).addComponent(IDLabel).addComponent(nombreAsignaturaLabel))
						.addGap(18, 18, 18)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(nombreAsignaturaTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 100,
										Short.MAX_VALUE)
								.addComponent(creditosTextField)
								.addComponent(IDTextField, javax.swing.GroupLayout.Alignment.TRAILING))
						.addContainerGap(244, Short.MAX_VALUE)));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel3Layout.createSequentialGroup().addGap(26, 26, 26)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(nombreAsignaturaLabel)
								.addComponent(nombreAsignaturaTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(creditosLabel)
								.addComponent(creditosTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(IDLabel).addComponent(IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jTabbedPane1.addTab("Asignatura", jPanel3);

		jLabelAnio.setText("Año:");

		jTextField3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField3ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(panelCurso);
		panelCurso.setLayout(jPanel4Layout);
		jPanel4Layout
				.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel4Layout.createSequentialGroup().addContainerGap().addComponent(jLabelAnio)
								.addGap(18, 18, 18).addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE,
										100, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(283, Short.MAX_VALUE)));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createSequentialGroup().addGap(25, 25, 25)
						.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabelAnio).addComponent(jTextField3,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(312, Short.MAX_VALUE)));

		jTabbedPane1.addTab("Curso", panelCurso);

		nombreGrupo.setText("Grupo:");

		nombreGrupoTextField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField2ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(panelGrupos);
		panelGrupos.setLayout(jPanel5Layout);
		jPanel5Layout
				.setHorizontalGroup(
						jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel5Layout.createSequentialGroup().addContainerGap()
										.addComponent(nombreGrupo).addGap(18, 18, 18)
										.addComponent(nombreGrupoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(272, Short.MAX_VALUE)));
		jPanel5Layout.setVerticalGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel5Layout.createSequentialGroup().addGap(25, 25, 25)
						.addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(nombreGrupo).addComponent(nombreGrupoTextField,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(312, Short.MAX_VALUE)));

		jTabbedPane1.addTab("Grupo", panelGrupos);

		jLabel5.setText("Nombre titulación:");

		jTextField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout
				.setHorizontalGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel6Layout.createSequentialGroup().addContainerGap().addComponent(jLabel5)
								.addGap(18, 18, 18).addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE,
										100, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(208, Short.MAX_VALUE)));
		jPanel6Layout.setVerticalGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel6Layout.createSequentialGroup().addGap(25, 25, 25)
						.addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel5).addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(312, Short.MAX_VALUE)));

		jTabbedPane1.addTab("Titulación", jPanel6);

		nombreAlumnosLabel.setText("Correo");

		apellidosAlumnosLabel.setText("Apellidos");

		apellidosAlumnosTextField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField15ActionPerformed(evt);
			}
		});

		nombreAlumnosTextField.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField16ActionPerformed(evt);
			}
		});

		correoAlumnosLabel.setText("Nombre");

		dniAlumnosLabel.setText("DNI");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(panelAlumnos);
		panelAlumnos.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(correoAlumnosLabel).addComponent(apellidosAlumnosLabel)
								.addComponent(dniAlumnosLabel).addComponent(nombreAlumnosLabel))
						.addGap(33, 33, 33)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
								.addComponent(nombreAlumnosTextField, javax.swing.GroupLayout.Alignment.LEADING,
										javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
								.addComponent(apellidosAlumnosTextField, javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(correoAlumnosTextField, javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(dniAlumnosTextField))
						.addContainerGap(184, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(26, 26, 26)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(nombreAlumnosTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(correoAlumnosLabel))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(apellidosAlumnosTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(apellidosAlumnosLabel))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(correoAlumnosTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(nombreAlumnosLabel))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(dniAlumnosTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(dniAlumnosLabel))
						.addContainerGap(191, Short.MAX_VALUE)));

		lista.add(apellidosAlumnosTextField);
		lista.add(apellidosAlumnosTextField);
		lista.add(apellidosAlumnosTextField);
		lista.add(apellidosAlumnosTextField);

		jTabbedPane1.addTab("Alumno", panelAlumnos);
		setDefaultCloseOperation(HIDE_ON_CLOSE);

		saveButton.setText("Guardar");
		saveButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		cancelButton.setText("Cancelar");
		cancelButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup().addComponent(saveButton)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 284,
										Short.MAX_VALUE)
								.addComponent(cancelButton))
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jTabbedPane1)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup().addGap(0, 394, Short.MAX_VALUE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(saveButton).addComponent(cancelButton)))
				.addGroup(
						layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(0, 23, Short.MAX_VALUE))));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField3ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField3ActionPerformed

	private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField2ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField2ActionPerformed

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField1ActionPerformed

	private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {// GEN-FIRST:event_jTabbedPane1StateChanged
		// TODO add your handling code here:

		selectedIndex = jTabbedPane1.getSelectedIndex();
		if (previousSelectedIndex != -1) {
			resetTextFields(jTabbedPane1.getComponentAt(previousSelectedIndex));
		}

		previousSelectedIndex = selectedIndex;
	}// GEN-LAST:event_jTabbedPane1StateChanged

	private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField15ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField15ActionPerformed

	private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField16ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField16ActionPerformed

	private void jTextField19ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField19ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField19ActionPerformed

	private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField20ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField20ActionPerformed

	private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField4ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField4ActionPerformed


	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
		boolean noVacio = true;
		PanelAlumno panelAlumno;

		for (int i = 0; i < 4; i++) {
			if (lista.get(i).getText().isEmpty()) {
				System.out.println(lista);
				noVacio = false;
			}
		}

		if (selectedIndex == 5 && noVacio) {
			
			panelAlumno = new PanelAlumno(_ctrl,crearAlumno());
			panelAlumno.open(ViewUtils.getWindow(this));
		}
		if (selectedIndex == 4 && noVacio) {
			crearCurso();
			
		}
		if (selectedIndex == 3) {
			crearGrupo();
		}
		if (selectedIndex == 1 && noVacio) {
			crearAsignatura();
		}
	}// GEN-LAST:event_jButton1ActionPerformed

	private void crearAsignatura() {
		int creditos = 0;
		String textoCreditos = creditosTextField.getText();
		try {
			creditos = Integer.parseInt(textoCreditos);
		} catch (NumberFormatException e) {
			System.out.println("Error: El valor ingresado no es un número entero.");
		}
		String nombre = nombreAsignaturaTextField.getText();
		String codigo = IDTextField.getText();
		_ctrl.altaAsignatura(new Asignatura(nombre, creditos, codigo, null));
	}

	private Alumno crearAlumno() {
		// TODO Auto-generated method stub
		String apellidos = apellidosAlumnosTextField.getText();
		String nombre = nombreAlumnosTextField.getText();
		String correo = correoAlumnosTextField.getText() + "@universidad.es";
		String dni = dniAlumnosTextField.getText();
		Alumno a = new Alumno(nombre, apellidos, dni, correo);
		_ctrl.altaAlumno(a);
		return a;
	}

	private void crearGrupo() {
		JDialog panelGrupo;
		String nombre = nombreGrupoTextField.getText();
		panelGrupo = new PanelAltaGrupo(_ctrl, nombre);
		((PanelAltaGrupo) panelGrupo).open(ViewUtils.getWindow(this));
	}

	
	private void crearProfesor() {
		// datos del profesor a crear
		String nombre = nombreProfesorTextField.getText();
		String apellidos = apellidosProfesorTextField.getText();
		String DNI = dniProfesorTextField.getText();
		String correo = correoProfesorTextField.getText() + "@prof.es";
		
		_ctrl.altaProfesor(new Profesor(nombre, apellidos, DNI, correo));
	}
	
	private void crearCurso() {
	    try {
	        int anio = Integer.parseInt(jLabelAnio.getText()); 
	        if (_ctrl.altaCurso(anio)) {  
	            JOptionPane.showMessageDialog(this, "Curso creado correctamente para el año: " + anio);
	            PanelCurso panelCurso = new PanelCurso(_ctrl);
	    	    panelCurso.open(padre);
	        } else {
	            JOptionPane.showMessageDialog(this, "No se pudo crear el curso, ya existe uno para ese año.", "Error de Creación", JOptionPane.ERROR_MESSAGE);
	        }
	    } catch (NumberFormatException e) {
	        JOptionPane.showMessageDialog(this, "Error: El valor del año debe ser un número entero.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
	    }
	}
	
	
	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		// TODO add your handling code here:
		this.setVisible(false);
	}// GEN-LAST:event_jButton2ActionPerformed


	private int previousSelectedIndex = -1;

	private void resetTextFields(Component component) {
		if (component instanceof JPanel) {
			JPanel panel = (JPanel) component;
			for (Component childComponent : panel.getComponents()) {
				if (childComponent instanceof JTextField) {
					JTextField textField = (JTextField) childComponent;
					textField.setText("");
				}
			}
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(DialogoAlta.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(DialogoAlta.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(DialogoAlta.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(DialogoAlta.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the dialog */
		/*
		 * java.awt.EventQueue.invokeLater(new Runnable() { public void run() {
		 * DialogoAlta dialog = new DialogoAlta(new javax.swing.JFrame(), true);
		 * dialog.addWindowListener(new java.awt.event.WindowAdapter() {
		 * 
		 * @Override public void windowClosing(java.awt.event.WindowEvent e) {
		 * System.exit(0); } }); dialog.setVisible(true); } });
		 */
	}

	private javax.swing.JButton saveButton;
	private javax.swing.JButton cancelButton;
	private javax.swing.JLabel nombreGrupo;
	private javax.swing.JLabel jLabelAnio;
	private javax.swing.JLabel nombreAsignaturaLabel;
	private javax.swing.JLabel creditosLabel;
	private javax.swing.JLabel IDLabel;
	private javax.swing.JLabel apellidosAlumnosLabel;
	private javax.swing.JLabel nombreAlumnosLabel;
	private javax.swing.JLabel correoAlumnosLabel;
	private javax.swing.JLabel dniAlumnosLabel;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel jLabel20;
	private javax.swing.JLabel jLabel21;
	private javax.swing.JLabel jLabel22;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JPanel panelAlumnos;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel panelCurso;
	private javax.swing.JPanel panelGrupos;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField creditosTextField;
	private javax.swing.JTextField IDTextField;
	private javax.swing.JTextField nombreAlumnosTextField;
	private javax.swing.JTextField apellidosAlumnosTextField;
	private javax.swing.JTextField correoAlumnosTextField;
	private javax.swing.JTextField dniAlumnosTextField;
	private javax.swing.JTextField jTextField19;
	private javax.swing.JTextField nombreGrupoTextField;
	private javax.swing.JTextField jTextField20;
	private javax.swing.JTextField jTextField21;
	private javax.swing.JTextField jTextField22;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField nombreAsignaturaTextField;
	private javax.swing.JTextField nombreProfesorTextField;
	private javax.swing.JTextField apellidosProfesorTextField;
	private javax.swing.JTextField correoProfesorTextField;
	private javax.swing.JTextField dniProfesorTextField;
	// End of variables declaration//GEN-END:variables
}
